# Generated by Django 3.1.7 on 2021-03-15 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='profile/%Y/%m/%d/')),
                ('description', models.TextField()),
                ('contact_no', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('date_of_bith', models.DateField()),
                ('occupation', models.CharField(max_length=100)),
                ('excerpt', models.CharField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
